all: 
	javac *.java
clean: 
	rm *.class
run: Coordinates.class main.class SlimeFinder.class
	java main
Coordinates.class: Coordinates.java
	javac Coordinates.java
main.class: main.java
	javac main.java
SlimeFinder.class: SlimeFinder.java
	javac SlimeFinder.java
